apiVersion: v1
kind: Pod
metadata:
  labels:
    app: citibank-service
spec:
  containers:
    - name: dind
      image: docker:18.05-dind
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
  volumes:
    - name: dind-storage
      emptyDir: {}
