apiVersion: v1
kind: Pod
metadata:
  labels:
    app: citibank-service
spec:
  containers:
    - name: alpine
      image: gliderlabs/alpine:3.3
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /var/lib/docker
          name: dind-storage
  volumes:
    - name: dind-storage
      emptyDir: {}
